### ISSUE TITLE
paginate?

### ISSUE THREAD

**Issue by Chukstart** [loris/api-query-params#101]
Can you use this for pagination or how would you use this together with pagination like for example how would you paginate would you need to use the page number before like so

`http://localhost:3000/api/tst/users/1/?_id=5d74d73ad8ba0e04f80ee346`
the **number 1** being the **page number**  
or after the query parameters although doing that after causes an error 
I'm a newbie I apologize for this question

**Comment by loris** [comment]
Hi @Chukstart, are you using a web framework such as Express? I will be able to provide you with code snippet.

**Comment by Chukstart** [comment]
> Hi @Chukstart, are you using a web framework such as Express? I will be able to provide you with code snippet.

Yes I'm using express and mongoose I'd really appreciate the code snippet

**Comment by loris** [comment]
Ok so the `1` in your URL (`http://localhost:3000/api/tst/users/1`) is not an URL query parameter but an URL path parameter, so you can use the library this way:

```
import express from 'express';
import aqp from 'api-query-params';
import User from './models/User';

const app = express();

app.get('/api/tst/users/:page', (req, res, next) => {
  const recordsPerPage = 10;
  const { filter, skip, limit, sort, projection, population } = aqp({ skip: req.params.page * recordsPerPage, ...req.query});
  ... // same as in the README.md example
});
```

In the example, I extract the page value from the `req.params` object, and build a virtual `skip` variable (which is page number * number of records per page, so if you're on a page 3, you will skip the first 30 records for instance), let me know if this is clear

**Comment by Chukstart** [comment]
> Ok so the `1` in your URL (`http://localhost:3000/api/tst/users/1`) is not an URL query parameter but an URL path parameter, so you can use the library this way:
> 
> ```
> import express from 'express';
> import aqp from 'api-query-params';
> import User from './models/User';
> 
> const app = express();
> 
> app.get('/api/tst/users/:page', (req, res, next) => {
>   const recordsPerPage = 10;
>   const { filter, skip, limit, sort, projection, population } = aqp({ skip: req.params.page * recordsPerPage, ...req.query});
>   ... // same as in the README.md example
> });
> ```
> 
> In the example, I extract the page value from the `req.params` object, and build a virtual `skip` variable (which is page number * number of records per page, so if you're on a page 3, you will skip the first 30 records for instance), let me know if this is clear

Doing this does not work when I change the page number the same records still appear I'm using it like this `http://localhost:3000/api/tst/users/1/?skip=1`

since using it like this 
`http://localhost:3000/api/tst/users/1/`

without the skip param gives me an empty array 
when I go to the second page nothing changes

**Comment by Chukstart** [comment]
> > Ok so the `1` in your URL (`http://localhost:3000/api/tst/users/1`) is not an URL query parameter but an URL path parameter, so you can use the library this way:
> > ```
> > import express from 'express';
> > import aqp from 'api-query-params';
> > import User from './models/User';
> > 
> > const app = express();
> > 
> > app.get('/api/tst/users/:page', (req, res, next) => {
> >   const recordsPerPage = 10;
> >   const { filter, skip, limit, sort, projection, population } = aqp({ skip: req.params.page * recordsPerPage, ...req.query});
> >   ... // same as in the README.md example
> > });
> > ```
> > 
> > 
> > In the example, I extract the page value from the `req.params` object, and build a virtual `skip` variable (which is page number * number of records per page, so if you're on a page 3, you will skip the first 30 records for instance), let me know if this is clear
> > @loris
> 
> Doing this does not work when I change the page number the same records still appear I'm using it like this `http://localhost:3000/api/tst/users/1/?skip=1`
> 
> since using it like this
> `http://localhost:3000/api/tst/users/1/`
> 
> without the skip param gives me an empty array
> when I go to the second page nothing changes
> like this `http://localhost:3000/api/tst/users/**2**/?skip=1`
> the same records still apear

Sorry sorry I've only just realized I have around 6 records and in your example you've used 10 records per page so THANKS it works as expected however how would I use this on the front end since I want to change the page number while still keeping the user's filters 

like so how would I do this  
`http://localhost:3000/api/tst/users/3/?featured=true` while changing the page number but still have the query params in place
