### ISSUE TITLE
Add option to Blacklist fields in populate

### ISSUE THREAD

**Issue by rrr-coders** [loris/api-query-params#103]
- I have a "Users" collection with a user's password stored it "password" field.

- I have another collection "Articles"  with the "_id" of the "User" collection as the foreign key  to "user" field in "Articles" collection

- I can then populate the "user" field in "Articles" collection and get the password of the user by passing in "user.password"

This  is a possible security flaw. It'd be great if you can provide a mechanism to overcome this.

**Comment by loris** [comment]
Hi @rrr-coders. I do understand your need, however I am not sure this should be in the scope of this package, nor its responsibility. It seems better that this package keep on just extracting some data (here the fields to be selected) and afterwards you have some business logic (for instance, you might want a superadmin to select the "password" fields, but not a normal user) to validate that the current user is authorized to select these fields.
Personnally, I do use the following library https://stalniy.github.io/casl/ to handle everything related to authorization, have a look at the `permittedFieldsOf` function
