### ISSUE TITLE
Handle deep populating

### ISSUE THREAD

**Issue by AlexandreMouyen** [loris/api-query-params#104]
I tried to populate in multiple levels but it seems it is not working.

Here example : https://medium.com/fredwong-it/mongoose-populate-multiple-levels-7e45be41d16b

**Comment by xinyangyuan** [comment]
Maybe add quotation mark syntax to specify the field that actually needs to be populated? 

Because the example is populated on `message` field and then populated on nested `replies.from` instead of all three. Maybe if we add support for single or double quotation to mark the parts of the query string that should be treated as an independent part:

```javascript
query = `populate=message.'replies.from'` \\or
query = `populate=message."replies.from"` 
```

I can try to do a pull request if others think this is helpful :)

**Comment by loris** [comment]
Hi @AlexandreMouyen can you provide you code which is not working? And ideally, with the URL you are testing with, the current output from `aqp` and the expected output. Thanks!

**Comment by AlexandreMouyen** [comment]
Hi,

Thanks for yours answers, but I'm not sure to understand.

This is my url : "/assets/Test Model?populate=contract,contract.supplier". It is correctly populating my contract, but not the supplier in my contract object.

**Comment by AlexandreMouyen** [comment]
Even more, I really want to do something like that :
```
Kitten.findOne().populate('owner').exec(function (err, kitten) {
  console.log(kitten.owner.name) // Max
})

Kitten.find().populate({
  path: 'owner',
  select: 'name',
  match: { color: 'black' },
  options: { sort: { name: -1 } }
}).exec(function (err, kittens) {
  console.log(kittens[0].owner.name) // Zoopa
})

// alternatively
Kitten.find().populate('owner', 'name', null, {sort: { name: -1 }}).exec(function (err, kittens) {
  console.log(kittens[0].owner.name) // Zoopa
})
```

Is it possible?

Thanks.

**Comment by loris** [comment]
Try this instead: `/assets/Test Model?populate=contract&fields=contract.supplier`. The collection you want populated is `contract`, then you only want to project the `supplier` field from that collection

**Comment by AlexandreMouyen** [comment]
Ok ok thanks for answer.
