### ISSUE TITLE
Querying for string with commas in value

### ISSUE THREAD

**Issue by pnewell** [loris/api-query-params#108]
Is there a built in way to handle querying for strings that include commas inside them? For example:

`thing=a,b,c`

In this case it will search the field thing for a value of `a`, `b` or `c`.

Instead, we need it to search the field thing for a value of `a,b,c`.

Just as a note, I've also attempted forcing a string for the whole value but that hasn't worked for me either:

`thing=string(a,b,c)`

**Comment by loris** [comment]
Hi @pnewell, this is a bug, `thing=string(a,b,c)` should work as you intend to. I commited a fix, will publish a new version asap
