### ISSUE TITLE
Strange string to number parsing

### ISSUE THREAD

**Issue by angelhodar** [loris/api-query-params#113]
Hey, I have had a strange bug with this, I dont know why but if you input this random id to the querystring like this:

```js
let { filter} = aqp({ uid: '115524599024168443300' }
```

The filter gets this as output:

```js
{ uid: 115524599024168440000 }
```

It somehow changes the last threes for zeros. Maybe its some type of overflow? I have solved it by setting that particular castParam to string, but I suppose you wanted to know it.

**Comment by loris** [comment]
Hi @angelhodar, thanks for the report!

Looks like some JavaScript quirks with number greater than MAX_SAFE_INTEGER
<img width="274" alt="image" src="https://user-images.githubusercontent.com/8362/90636893-8de09c00-e22b-11ea-9776-1d40b3340910.png">

**Comment by loris** [comment]
Will use [isSafeInteger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger) in next release

<img width="446" alt="image" src="https://user-images.githubusercontent.com/8362/90637668-95547500-e22c-11ea-8f2e-e5e35ecf9edf.png">

**Comment by angelhodar** [comment]
@loris Perfect! Glad it helped. Forntunately its very unusual to happen!!
