### ISSUE TITLE
[request] Option to disable automatic casters

### ISSUE THREAD

**Issue by icetbr** [loris/api-query-params#115]
Hi, I don't like the unpredictability that automatic casting adds to the application. I may have dozens of string fields and in some of them the user might decide to use only numbers. I don't want to have to declare all my string fields explicitly (`castParams`)

Might you include an option to disable automatic casters?

**Comment by loris** [comment]
Hi @icetbr thanks for the feature request. I just published a new version where the built-in casters are customizable using the `casters` option. Have a look at the following unit test for usage:

```
test('filter: customize built-in casters', (t) => {
  const res = aqp('key1=10&key2=true&key3=VALUE', {
    casters: {
      number: (val) => val,
      boolean: (val) => (val === 'true' ? '1' : '0'),
      string: (val) => val.toLowerCase(),
    },
  });
  t.truthy(res);
  t.deepEqual(res.filter, { key1: '10', key2: '1', key3: 'value' });
});
```

Here the `number: (val) => val` line is used to disable how strings detected as number are casted (the same value is returned without any casting).

Let me know if this work for you.

**Comment by icetbr** [comment]
Hi, I will test it soon enough, but it seems perfect. Thank you very much.
