### ISSUE TITLE
+ in the query parameter is stripped

### ISSUE THREAD

**Issue by manishbhatias** [loris/api-query-params#117]
I am trying to send a E.164 formatted phone number in query string. 

Sample HTTP request
```
GET /api/nonprofits/?members.phone=%2B919831042144 HTTP/1.1
```

After parsing with api-query-params, the + in the param is stripped and I get this as a log for filter object
```
{ 'members.phone': 919831042144 }
```

It seems to be auto casting it to a number and therefore removing the + from the value. 

Should values starting with + be considered numbers or should the check for numbers be made stricter? I think I can specify casters per key to override this but just wanted to understand why it is done this way

**Comment by loris** [comment]
Hi @manishbhatias, indeed the code think by default that `+123` is an integer (a positive one, like `-456` is a negative integer). You can use the `castParams` options to define the `members.phone` property as string:

```
> aqp('members.phone=%2B33612345', { castParams: { 'members.phone': 'string' } });
{ filter: { 'members.phone': '+33612345' } }
```
