### ISSUE TITLE
Special character's not matching

### ISSUE THREAD

**Issue by rajinikumar-prowesssoft** [loris/api-query-params#120]
I am passing the special characters but it replaced as special characters.
Exmaple:

```
const aqp = require('api-query-params');
const q = {mobile_no : "+919876543210"};
const result  = aqp(q);
console.log(result);
```

Current Output:
`{ filter: { mobile_no:  919876543210 } }`

Expected Output:

`{ filter: { mobile_no: +919876543210 } }`

**Comment by loris** [comment]
Hi @rajinikumar-prowesssoft please have a look at this issue: https://github.com/loris/api-query-params/issues/117#issuecomment-725678401

**Comment by rajinikumar-prowesssoft** [comment]
Thanks alot.
