### ISSUE TITLE
Cannot use regex in filter with the $or operator

### ISSUE THREAD

**Issue by Yandawl** [loris/api-query-params#121]
Hey there, I would like to use regex with the $or operator.

```aqp('filter={"$or":[{"name_en":/^value/},{"name_fr":/^value/}]}'); // string comes directly from the query string```

Unfortunately this produces the following error:

`Invalid JSON string: {"$or":[{"name_en":/^value/},{"name_fr":/^value/}]}`

Regex is correctly parsed when used on a single field, but I need to use it on multiple using conditions. Is there a workaround for this?

Many thanks

**Comment by loris** [comment]
Hi @Yandawl, unfortunately regex literals are not valid JSON.
One workaround is to use the [$regex mongo operator](https://docs.mongodb.com/manual/reference/operator/query/regex/):

`{"$or":[{"name_en":{"$regex":"^value"}},{"name_fr":{"$regex":"^value"}}]}`
