### ISSUE TITLE
order of query params resolves to different results

### ISSUE THREAD

**Issue by uL1111** [loris/api-query-params#133]
**Short description**
When passing a different order of query parameters, the output will be different. I assume, query params are sequence order insensitive. If you disagree about my assumption, this issue is meaningless to you.

**Example**
```
// variant 1: NE before EQ
const query = aqp('type!=10a&type=20b');

//  {
//    filter: {
//      type: '10a'
//    },
//  }
```
```
// variant 2: EQ before NE
const query = aqp('type=10a&type!=20b');

//  error: 'Cannot create property '$ne' on string '10a'
```

**Code debugging**
When you change the order of "equals" `=` and "not equals to" `!=`, the query parser will fail due to internal parser logic:
`'Cannot create property '$ne' on string '10a''`. Both variants are kinda wrong. So far, my debugging resolves to the method `getFilter`.

Variant 1: The first iteration will lead to an operator === '$ne' and assign the value like `result[key][op] = value`. The second iteration will lead to `operator === '$eq' and will reassign like `result[key] = value`. Therefore the later iteration will override the first one. Is this intentional?

Variant 2: The first iteration will lead to an operator === '$eq' and it will assign the value like `result[key] = value`. The second iteration, will lead to operator === '$ne' and therefore reaches the default/else case `result[key][op] = value`. The last statement will create the previously announced error message, because `result[key]` is already a sting value from the first iteration.

**Upcoming**
A quick solution from our team was to use always the specific operator and create always the operator specific filter:
```
...
} else if (op === '$eq') {
      result[key][op] = value;
} ...
```

Please give feedback about this topic and provide a roadmap/fix to satisfy this requirement.

**Comment by loris** [comment]
Hi @uL1111, thanks for the detailed bug fix, please check v5.3.1, it should be fixed
