### ISSUE TITLE
Ability to map filter operators

### ISSUE THREAD

**Issue by unlight** [loris/api-query-params#45]
Create ability to customize filter keys. May be useful for other orm.
For example:
`count>5`
`{filter: {count: {gt: 5}}}`
Key `gt` without `$`

**Comment by loris** [comment]
I have been thinking about extending the project to support more ORMs. Which one are you interested in, in particular? I will have a look at the query DSL

**Comment by unlight** [comment]
I haven't chosen yet :baby_chick: 
I just created this issue in advance...

[Orm caminte](https://github.com/biggora/caminte/wiki/Query-Interface#queries) uses query operator keys without `$`
I think, you can ignore this issue. Most likely, I will not use caminte orm.
Other orms has pretty enough support of mongodb query interface.
