### ISSUE TITLE
$in queries not generated correctly for ObjectIds types

### ISSUE THREAD

**Issue by damasioalexandre** [loris/api-query-params#81]
When running a query such as api/strore?owner=5996e60a6097712268bcfcb5,599999990e58541d229ef318

generates the query: 
{ owner: { $in: [ "5996e60a6097712268bcfcb5", "599999990e58541d229ef318" ] } }

It should generate the query as follows:
{ owner: { $in: [ ObjectId("5996e60a6097712268bcfcb5"), ObjectId("599999990e58541d229ef318") ] } }

I am passing the following to the method:

var agpOptions = {
        casters: {
            mongoId: val => mongo.ObjectId(val)
        },
        castParams: {
            _id: 'mongoId',
            owner: 'mongoId'
        }
    };

var parsedQuery = aqp(queryString, agpOptions);

**Comment by loris** [comment]
Hi @damasioalexandre, sorry for the delay I was on holidays!
Can you try again with the latest version (`4.3.1`), custom casters should now be properly applied on array items
