### ISSUE TITLE
aqp is not a function afterr upgrading from 4.5.1 to 4.8.0

### ISSUE THREAD

**Issue by eyp** [loris/api-query-params#90]
const aqp = require('api-query-params')

Just calling aqp from any method I got this error:

TypeError: apq is not a function

Tested on node 8.9.4 and 10.10.0. And know the I don't give any details, but I don't get more information on this.

**Comment by loris** [comment]
Hi @eyp, sorry about that. Please try 4.8.1

**Comment by eyp** [comment]
4.8.1 works fine. Thank you again.
