### ISSUE TITLE
how to use tarball from github?

### ISSUE THREAD

**Issue by lager1** [loris/api-query-params#91]
I've forked this project to do some minor changes, which are specific for my project. I've recently updated a lot of project dependencies including api-query-params. With new version of npm I've run into problems with editing api-query-params code directly so I wanted some clean solution.

After forking api-query-params and adding fork url in `package.json` in my project the package installs fine, but the installed package looks a lot different - basically a copy of github repo. When i try to launch the whole app i just get `Error: Cannot find module 'api-query-params'`.

I figured out that the source needs to be built, but im totally lost what to do next to use my fork by npm in `package.json` to be installed as it should and to just work as before. 

Can you please provide steps how to build package that can be used in `package.json` from github tarball?

**Comment by loris** [comment]
Hi @lager1, have you tried to build your fork? This way: go inside the `node_modules/api-query-params` folder, then type `npm install && npm build`. It should build the package and output it inside a `dist` folder (and your app will use this).
That build step is done for you when you get the package from `npm` but not from `github`
Hope this helps

**Comment by loris** [comment]
By the way, I am interested in your specific needs and why you had to fork the project. I just had a look at the commits you have done on your fork and I am not sure which new needs it covers. Apparently you are trying to make the code handle dates which are formatted this way: `YYYY-MM-DD` but the master project should already handle it. Have a look at this existing test case: 

```
test('filter: date casting', t => {
  const res = aqp('key1=2016-04&key2=2016-04-12&key3=2016-04-02 08:00');
  t.truthy(res);
  t.deepEqual(res.filter, {
    key1: new Date('2016-04'),
    key2: new Date('2016-04-12'),
    key3: new Date('2016-04-02 08:00'),
  });
});
```

Am I missing something else you are trying to achieve?

**Comment by lager1** [comment]
Thanks for quick response. The fork actually needs to handle two types of dates:
- ISO 8601 eg. `/api/?timestamp=2018-10-05T14:55:51.655Z`
- and also `YYYY-MM-DD`

I wrote this patch like 2 years ago so I'm not totally sure about the support of this at the time of patching but as far as I'm aware the ISO 8601 is not supported. It might be nice for someone to use this feature if you would like to add it, but I still think that my patch is very specific to my needs (see for example https://github.com/lager1/api-query-params/blob/master/src/index.js#L83 ).

After running `npm run build` i got some files in api-query-params directory:
```
dist/
dist/cjs
dist/cjs/index.js
```
My `package.json` uses the dependency as ` "api-query-params": "https://github.com/lager1/api-query-params/tarball/master",`. I wanted to keep the source and the build separate, so my thought was i could build it from the forked repo and then use the tarball to install it with npm, but that kind of does not make sense. Is it possible to run build when installing the package with npm? That could potentially solve the problem for me if this correctly builds the source and creates correct file structures.


When comparing just the file structure after first installing api-query-params - https://github.com/CESNET/etlog/tree/d4f2329a042f1a0d683421965489e09173499ed3/node_modules/api-query-params and after i forked the repostiory and tried to use it - https://github.com/CESNET/etlog/tree/master/node_modules/api-query-params 
These two structures are very different. Can i somehow achieve the "clean" one somehow with using github as source? Hope it's clear what I'm trying to achieve.

**Comment by lager1** [comment]
I've added the built source to the forked repository and it now works with github tarball. It's not as clean as I wanted it to, but it works so I'm closing the issue.
