### ISSUE TITLE
Project specific array elements in the returned array

### ISSUE THREAD

**Issue by lapidus** [loris/api-query-params#93]
Does the library support this projection?
https://docs.mongodb.com/manual/tutorial/project-fields-from-query-results/#project-specific-array-elements-in-the-returned-array

Such as slicing the last element of an array field:
> db.inventory.find( { status: "A" }, { item: 1, status: 1, instock: { $slice: -1 } } )

If not, it would be amazing if it could :) 

Thank you!

**Comment by loris** [comment]
Hi @lapidus,

Thanks for the issue, I didn't know about those special projection operators!

Not sure how to add this into the URL query parameters API though, especially to handle the `$elemMatch` projection operator which can be really expressive.

One idea could be to allow JSON into the `fields` parameter, like this:
`https://api.domain.com/items?status=A&fields={"item":1,"status":1,"instock":{"$slice":-1}}`
This would allow to express more complicated [`$elemMatch` projection](https://docs.mongodb.com/manual/reference/operator/projection/elemMatch/#proj._S_elemMatch) like this:
`https://api.domain.com/items?zipcode=63109&fields={"students":{"$elemMatch":{"school":102}}}`

**Comment by lapidus** [comment]
Thank you, yes, I think it would excellent if it could take JSON 👍 
Is it something you have time to look into or should we try to work on a PR from this side?

**Comment by loris** [comment]
Hi @lapidus, just published `4.9.0` with added support for JSON string in the projection field. Let me know if it fits your need.
