### ISSUE TITLE
Querying by string with / incorrectly parsed

### ISSUE THREAD

**Issue by threewordphrase** [loris/api-query-params#95]
I am trying to filter by a string that contains one of more `/` characters.

Query: `{key: 'This key/has special chars!'}`

Where the `console.log`s are:
```
console.log(ctx.query)
const { filter, skip, limit, sort, projection } = aqp(ctx.query)
console.log(filter)
```

What that `console.log` looks like:
```
{ key: 'This key/has special chars!' }
{ key: { '$in': [ 'This key', 'has special chars!' ] } }
```

Expected result: the string for `key:` is preserved as a single string for the mongoose query.

**Comment by threewordphrase** [comment]
After reading through the code, it looks like this regex parsing is pretty deeply a part of `aqp`. I fixed my particular case with the following override (for extra confusion, my key is actually named `key`, for s3 objects ;) ):

```
const { filter, skip, limit, sort, projection } = aqp(ctx.query)
if (ctx.query.key) filter.key = ctx.query.key
```

An option to disable regex parsing for particular keys, similar to the custom caster handling, would be a nice feature.

**Comment by loris** [comment]
Hi @threewordphrase,

Sorry for the delay, I was off for 2 weeks. Thanks for your issue report, actually you discovered a bug in the way the split of value by comma was working. I fixed it in `4.10.0` and your use case should now work properly. Let me know.

**Comment by loris** [comment]
@threewordphrase Forgot about the important stuff, your use case:

It will work properly if the value contains slashes but do not look like a regex:

> aqp('key=This key/has special chars!').filter
{ key: 'This key/has special chars!' }

But if it does (ie, starting/ending with slashes), it will be automatically casted to a regex:

> aqp('key=/This key/has special chars!/').filter
{ key: /This key\/has special chars!/ }

To avoid that, you could either force string casting at the query level:

> aqp('key=string(/This key/has special chars!/)').filter
{ key: '/This key/has special chars!/' }

Or at the configuration level:

> aqp('key=/This key/has special chars!/', { castParams: { key: 'string' } }).filter
{ key: '/This key/has special chars!/' }

**Comment by threewordphrase** [comment]
Thank you @loris !
